name: igdesign
channels:
  - pyg
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - brotli-python=1.1.0
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - lightning=2.2.0.post0
  - lightning-utilities=0.10.1
  - openssl=3.2.1
  - pyg=2.4.0
  - python=3.11.7
  - pytorch=2.1.2
  - pytorch-cuda=12.1
  - pytorch-lightning=2.1.3
  - pytorch-mutex=1.0
